// =============================================================================
// Deployment: fabric-private-connectivity, prod (EXAMPLE VALUES)
//
// In the private deployment repo, this file holds the real Deployment Context.
// Nothing here is secret, but subscription IDs, names, and IP ranges are a map
// of your network, so they don't belong in a public repo.
//
// The `using` path points at the product checked out from the public repo at
// a pinned tag (see azure-pipelines.yml).
// =============================================================================

using '../../products/platform/fabric-private-connectivity/main.bicep'

// ---- Deployment Context ------------------------------------------------------
param environment = 'prod'
param location = 'southcentralus'

param proxySubnetResourceId = '/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-network-prod/providers/Microsoft.Network/virtualNetworks/vnet-contoso-prod/subnets/snet-fabric-proxy-prod'
param plsSubnetResourceId = '/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-network-prod/providers/Microsoft.Network/virtualNetworks/vnet-contoso-prod/subnets/snet-fabric-pls-prod'
param plsSubnetAddressPrefix = '10.100.1.0/27'

param logAnalyticsWorkspaceResourceId = '/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-monitor-prod/providers/Microsoft.OperationalInsights/workspaces/law-contoso-prod'

param tags = {
  WorkloadClassification: 'shared-platform'
  DataClassification: 'restricted'
  BusinessOwner: 'data-platform-team'
  TechnicalOwner: 'cloud-platform-team'
  Worktag: 'CC0000'
  Ticket: 'REQ-0000'
}

// ---- Product Configuration ---------------------------------------------------
// Generated by scripts/render.py. Edit destinations.yaml, never this value.
param destinations = loadJsonContent('out/destinations.json').destinations

param adminSshPublicKey = 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIExampleKeyReplaceMeExampleKeyReplaceMe0000 break-glass'
param managementSourcePrefixes = [
  '10.100.9.0/26' // Bastion subnet
]
param dnsServerIps = []
